### ISSUE TITLE
Title/Content for talk in Interoperability and Federation Across Bioinformatic Platforms and Resources workshop at PAG 2018

### ISSUE THREAD

**Issue by sammyjava** [LegumeFederation/Meetings#1]
I have managed to convince the workshop organizer to allow us to present at this workshop, so here's an issue to establish what the talk will be titled and what it will contain.

I'd be happy to do another task-solving talk a la ICLGG 2017 (aka "scavenger hunt") to show off our federated resources, but that's just one suggestion. Perhaps we want to focus on the most recent tools that relate to the workshop topic.

**Comment by elyons** [comment]
Awesome news, Sam!  :)

I also contacted Carolyn Dill about speaking in her workshop and that looks like a yes as well.

For the interop and federation talk, maybe a meta talk on using the scavenger hunt to show off federated resources?  Or how federated resources let researchers answer more complex questions using the scavenger hunt as an example?  I feel that the audience is more interested  in federation and interop, rather than a typical legume researcher (keeping in mind that research questions drive the development of the federated resources).

Best,
-eric

---------------------------------------------------
Eric Lyons, Ph.D.

Associate Professor
Bio5 Institute
CyVerse PI 
School of Plant Sciences
University of Arizona, Tucson

Phone:  520-626-5070
Email: elyons.uoa@gmail.com
SkypeID:  ericlyons

Website: http://lyonslab.net
CoGe:  http://genomevolution.org
CyVerse:  http://cyverse.org

**Comment by sammyjava** [comment]
https://github.com/LegumeFederation/Meetings/blob/master/PAG2017-Sam-workshop-talk.md
