### ISSUE TITLE
BIC LegFed talk and poster

### ISSUE THREAD

**Issue by ekcannon** [LegumeFederation/Meetings#3]
Draft presentation is here:
https://docs.google.com/presentation/d/1MlibTy3_HMbrMvDQEG4DsXOXdvqUmr4sHiPSBaGHHMM

**Comment by adf-ncgr** [comment]
Hi Ethy-
thanks for sharing; I am going to send you some rough slides I had made a long time ago around the flowering time use case in common bean, which may or may not be of any help in developing the story (note my use of CMTV could now be replaced with the same thing in cmap-js).

What I noticed comparing my slides to yours is that you started with Dt1 which lands on soybean genetic map "L"  = Chr19 then something happens on slide 23 and you end up on Chr03 in soybean (homeologous to Chr19). I had started from the tree and also ended up on Chr03=linkage group "N", but this was due to Chr03 looking like it had more retained gene content close to the Phavu chromsome; Chr19 appears also in the GCV view and I guess I should have taken that path to get to the better genetic map (as per my somewhat disappointed comment on the last slide in the notes section "a nearby marker puts us in to the genetic map and the consensus map with QTLs; some for  plant height are nearby, but not as clear a connection as one might wish".)

anyway, hope this helps...

**Comment by adf-ncgr** [comment]
went ahead and uploaded the old slides to the googledoc folder; really just a series of screenshots but if you open with google slides you'll see the comments in the notes panes explaining the flow; I think this link will open it in the desired fashion:
https://docs.google.com/presentation/d/1DgQ6E1i4ArfQOx_7lRO7uchlL9fXBdDnZgVHLJB-KOU/edit#slide=id.p3

**Comment by adf-ncgr** [comment]
maybe should also note that I have this use case on the brain again because Sudhansu had pointed me to a possibility for the ICRISAT talk driven by a publication in pigeonpean that describes the Tfl1 orthologue there (and see this fig. for an appearance of common bean as well https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4236620/figure/Fig8/ )

**Comment by ekcannon** [comment]
Hmm. Dt1 is producing odd results:

- Dt1 shows up on linkage group L in the genetic map (= chr19).
- Searching for "Dt1" in GBrowse at Soybase places it on chr03, not chr19, but does associate it with TFL1.
- When searching "Dt1" from SoyBase home page, the "gene call" cell links to a table of several possible gene models for Dt1, none of which fall on chr19 ... or chr03.

I really want to start at SoyBase to show that we are federated, and not do all of the investigation inside LegumeInfo.

**Comment by sammyjava** [comment]
FYI, since I've got my grubby mitts on the SB database, here's the LG and QTL associations for Dt1. It is not placed on a chromosome.
```
Dt1	GmClassical_L-CLG5	71.00
Dt1	GmComposite1999_L	105.70
Dt1	GmComposite2003_L	89.13
Dt1	GmMLG-JES_CxH8	0.00
Dt1	GmRFLP-Chiba2_L	108.40
Dt1	GmRFLP-GA1996a_L	122.20
Dt1	GmSSR-Nebraska_L	99.90
Dt1	GmSSR-USDAARS-PBC_SSR8	1.80
Dt1	GmSSR-Utah_L	92.50
```
```Dt1	Carbon isotope discrimination 1-5
Dt1	Flower number 1-10
Dt1	Leaflet area 6-3
Dt1	Lodging 4-2
Dt1	Lodging 4-3
Dt1	Lodging 8-4
Dt1	Lodging 9-5
Dt1	Plant height 13-8
Dt1	Plant height 4-2
Dt1	Plant height 4-4
Dt1	Plant weight, dry 1-2
Dt1	Pod maturity 13-6
Dt1	Reproductive stage length 4-6
Dt1	Seed oil 23-4
Dt1	Seed weight 15-7
Dt1	Seed weight 3-5
Dt1	Seed width 1-7
Dt1	Seed width 1-7
Dt1	Seed yield 11-6
Dt1	Shoot weight, dry 4-3
```

**Comment by ekcannon** [comment]
No longer relevant?
